name: Python Script Workflow

on: [push]

permissions:
  contents: write

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
      
      - name: Execute Python Script
        run: |
          python web_scraping.py

      - name: Commit and Push Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add downloads/
          git add Parsed_PDFs.zip
          git commit -m "Update PDFs and ZIP files [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}